weight_decay: 0.0001
init_lr: 0.03
target_lr: null
ramp_up_epoch: 1
cache_dir: 'video_pub_cache'
instance_t: 0.07
instance_k: 4096 # number of neighbor embeddings to evaluate
kmeans_k: '2' # number of different clusters
trn_use_mean: True
num_frames: 15
img_emb_size: 128
resume: False
batch_size: 2
val_batch_size: 2
test_batch_size: 2
val_num_clips: 5
clstr_update_fre: null
part_vd: null
db_name: 'vd_unsup_fx'
col_name: 'dyn_clstr'
kNN_val: 10
fre_filter: 50
fre_cache_filter: 50
fre_valid: 50
fre_metric: 50
vd_3dresnet_IR:
  exp_id: 'vd_3dresnet_IR'
  task: 'IR'
  lr_boundaries: null
  train_num_workers': 1
  val_num_workers: 1
  train_num_steps: 100
  load_exp: null
  load_step: null
vd_3dresnet:
  exp_id: 'vd_3dresnet'
  task: 'LA'
  lr_boundaries: '974946,1304998'
  train_num_workers': 1
  val_num_workers: 1
  train_num_steps: 200
  load_exp: 'vd_unsup_fx/dyn_clstr/vd_3dresnet_IR'
  load_step: 100
