weight_decay: 1e-4
init_lr: 0.03
target_lr: None
ramp_up_epoch: 1
cache_dir: 'video_pub_cache'
fre_metric: 50
instance_t: 0.07
instance_k: 4096
kmeans_k: 100
num_classes: 2
trn_use_mean: True
vd_3dresnet_IR:
  db_name: 'vd_unsup_fx'
  col_name: 'dyn_clstr'
  batch_size: 2
  test_batch_size: 2
  test_no_frames: 5
  kNN_val: 10
  fre_filter: 50
  fre_cache_filter: 50
  fre_valid: 50
  dataset: 'kinetics'
  train_prep: 'ColorJitter_112'
  port: 27007
  exp_id: 'vd_3dresnet_IR'
  model_type: '3dresnet'
  task: 'IR'
  lr_boundaries: None
  train_num_workers': 1
  val_num_workers: 1
  train_num_steps: 100
vd_3dresnet:
  db_name: 'vd_unsup_fx'
  col_name: 'dyn_clstr'
  batch_size: 2
  test_batch_size: 2
  test_no_frames: 5
  kNN_val: 10
  fre_filter: 50
  fre_cache_filter: 50
  fre_valid: 50
  dataset: 'kinetics'
  train_prep: 'ColorJitter_112'
  port: 27007
  exp_id: 'vd_3dresnet'
  model_type: '3dresnet'
  task: 'LA'
  lr_boundaries: '974946,1304998'
  train_num_workers': 1
  val_num_workers: 1
  train_num_steps: 200
  load_exp: 'vd_unsup_fx/dyn_clstr/vd_3dresnet_IR'
  load_step: 100
