vgg_out_shape: '4096'
weight_decay: 0.0001
init_lr: 0.03
target_lr: null
ramp_up_epoch: 1
cache_dir: 'checkpoints'
instance_t: 0.07
instance_k: 4096 # number of neighbor embeddings to evaluate
num_classes: 2 # number of different clusters
trn_use_mean: True
num_frames: 15
emb_dim: 128
resume: False
batch_size: 32
val_batch_size: 32
test_batch_size: 32
val_num_clips: 5
test_num_clips: 5
clstr_update_fre: null
part_vd: null
dropout_rate1: 0.3
dropout_rate2: 0.15
kNN_val: 50
kNN_test: 50
fre_filter: 50
fre_cache_filter: 50
fre_valid: 50
fre_metric: 50
train_log_file: 'log.txt'
val_log_file: 'val_log.txt'
test_log_file: 'test_log.txt'
train_steps: 'vd_3dresnet_IR,vd_3dresnet'
vd_3dresnet_IR:
  exp_id: 'vd_3dresnet_IR'
  task: 'IR'
  lr_boundaries: null
  train_num_workers': 1
  val_num_workers: 1
  train_num_steps: 3000
  load_exp: null
  load_step: null
vd_3dresnet:
  exp_id: 'vd_3dresnet'
  task: 'LA'
  lr_boundaries: '974946,1304998'
  train_num_workers': 1
  val_num_workers: 1
  train_num_steps: 4000
  load_exp: 'vd_3dresnet_IR'
