vgg_out_shape: '4096' # output shape of feature extractor
weight_decay: 0.0001 # loss function weight decay
init_lr: 0.03 # optimizer initial learning rate
target_lr: null # optimizer target learning rate
ramp_up_epoch: 1 # learning rate ramp up epoch
cache_dir: 'checkpoints' # directory to save model checkpoints
instance_t: 0.07 # temperature for contrastive loss
num_classes: 2 # number of different clusters
num_frames: 15 # number of frames in each clip
middle_dim: 512 # middle layer dimension in the unpie network
emb_dim: 128 # final embedding dimension
img_height: 1080 # video frame height
img_width: 1920 # video frame width
batch_size: 32 # training batch size
inference_batch_size: 32 # val/test batch size
inference_num_clips: 5 # number of clips to sample from each video
clstr_update_fre: null # frequency to recompute clusters, default is 1 epoch
kNN_inference: 50 # number of nearest neighbors to consider
instance_k: 4096 # background neighbors to sample
fre_save_model: 50 # frequency to save model checkpoint (epochs)
fre_valid: 50 # frequency to validate model (epochs)
train_log_file: 'log.txt' # training log file
val_log_file: 'val_log.txt' # validation log file
test_log_file: 'test_log.txt' # test log file
train_steps: 'IR,LA' # training steps
IR:
  task: 'IR' # task name
  lr_boundaries: null # learning rate boundaries
  train_num_workers': 1 # number of workers for training data loader
  val_num_workers: 1 # number of workers for validation data loader
  train_num_steps: 1000 # number of training epochs
  load_task: null # load task
  load_step: null # load step
LA:
  task: 'LA'
  lr_boundaries: '974946,1304998'
  train_num_workers': 1
  val_num_workers: 1
  train_num_steps: 2000
  load_task: 'IR'
